services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      # enables hot reloading
      - ./frontend/src:/usr/share/nginx/html
    depends_on:
      backend:
        condition: service_healthy

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/song_rating_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 2s
      retries: 10
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: song_rating_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
