services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/html:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    container_name: frontend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: node .
    container_name: backend
