services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/html:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: node .
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/song_rating_db
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: song_rating_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
